MODELS = [
    'google/owlv2-base-patch16-ensemble',
    'google/owlv2-large-patch14-ensemble',
    'google/owlvit-base-patch32',
    'google/owlvit-large-patch14',
    'omlab/omdet-turbo-swin-tiny-hf',
    'IDEA-Research/grounding-dino-tiny',
    'IDEA-Research/grounding-dino-base'
]

NICKNAMES = {
    'google-owlv2-base-patch16-ensemble': 'OWLv2 Base',
    'google-owlv2-large-patch14-ensemble': 'OWLv2 Large',
    'google-owlvit-base-patch32': 'OWL-ViT Base',
    'google-owlvit-large-patch14': 'OWL-ViT Large',
    'omlab-omdet-turbo-swin-tiny-hf': 'OmDet',
    'IDEA-Research-grounding-dino-tiny': 'Grounding DINO Tiny',
    'IDEA-Research-grounding-dino-base:': 'Grounding DINO Base',
    'google/owlv2-base-patch16-ensemble': 'OWLv2 Base',
    'google/owlv2-large-patch14-ensemble': 'OWLv2 Large',
    'google/owlvit-base-patch32': 'OWL-ViT Base',
    'google/owlvit-large-patch14': 'OWL-ViT Large',
    'omlab/omdet-turbo-swin-tiny-hf': 'OmDet',
    'IDEA-Research/grounding-dino-tiny': 'Grounding DINO Tiny',
    'IDEA-Research/grounding-dino-base': 'Grounding DINO Base'
}

FOODS = [
    'background',
    'candy',
    'egg tart',
    'french fries',
    'chocolate',
    'biscuit',
    'popcorn',
    'pudding',
    'ice cream',
    'cheese butter',
    'cake',
    'wine',
    'milkshake',
    'coffee',
    'juice',
    'milk',
    'tea',
    'almond',
    'red beans',
    'cashew',
    'dried cranberries',
    'soy',
    'walnut',
    'peanut',
    'egg',
    'apple',
    'date',
    'apricot',
    'avocado',
    'banana',
    'strawberry',
    'cherry',
    'blueberry',
    'raspberry',
    'mango',
    'olives',
    'peach',
    'lemon',
    'pear',
    'fig',
    'pineapple',
    'grape',
    'kiwi',
    'melon',
    'orange',
    'watermelon',
    'steak',
    'pork',
    'chicken duck',
    'sausage',
    'fried meat',
    'lamb',
    'sauce',
    'crab',
    'fish',
    'shellfish',
    'shrimp',
    'soup',
    'bread',
    'corn',
    'hamburg',
    'pizza',
    ' hanamaki baozi',
    'wonton dumplings',
    'pasta',
    'noodles',
    'rice',
    'pie',
    'tofu',
    'eggplant',
    'potato',
    'garlic',
    'cauliflower',
    'tomato',
    'kelp',
    'seaweed',
    'spring onion',
    'rape',
    'ginger',
    'okra',
    'lettuce',
    'pumpkin',
    'cucumber',
    'white radish',
    'carrot',
    'asparagus',
    'bamboo shoots',
    'broccoli',
    'celery stick',
    'cilantro mint',
    'snow peas',
    ' cabbage',
    'bean sprouts',
    'onion',
    'pepper',
    'green beans',
    'French beans',
    'king oyster mushroom',
    'shiitake',
    'enoki mushroom',
    'oyster mushroom',
    'white button mushroom',
    'salad',
    'other ingredients'
]