name: findthefood
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - conda-forge::transformers
  - pillow
  - conda-forge::opencv
  - scipy
  - plotly::plotly
