name: findthefood
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pytorch
  - torchaudio
  - torchvision
  - transformers
  - pillow
  - scipy
  - plotly
  - pip:
    - opencv-python
